kind: pipeline
type: docker
name: default

steps:
- name: publish to docker
  image: plugins/docker
  settings:
    username:
      from_secret: docker_user
    password:
      from_secret: docker_password
    repo: hub.docker.com/r/jacob1123/imap-backup
    tags:
      - latest
